### ISSUE TITLE
Person Hall dataset

### ISSUE THREAD

**Issue by cdcseacave** [AIBluefisher/GraphSfM#11]
Hi,
Can you please provide Person Hall images you used in your tests? We want to be able to compare to your results.
Thank you!

**Comment by AIBluefisher** [comment]
The person hall dataset is provided by colmap, you can found it from https://colmap.github.io/datasets.html ,

and the other images from https://drive.google.com/drive/folders/0B0XWe1u3AJHFYTAyNGlHYXZhcnc .

I am sorry that I can't provide the aerial image datasets because of commercial protocol.

**Comment by cdcseacave** [comment]
Thank you!

For Person Hall, if is the same dataset from COLMAP, they provide also a
youtube video with the full dataset reconstruction. However in your tests
you report they reconstruct only 20 images. Did you modify the dataset in
any way?

Thanks for the google drive link, but I require access.

**Comment by AIBluefisher** [comment]
Colmap can reconstruct all the images, some of the data is not updated. I also can't access the link in China right now.
