### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by LumanYang** [AIBluefisher/GraphSfM#14]
CMake Error at cmake_install.cmake:61 (file):
  file INSTALL cannot find "/home/sunny/GraphSfMcolmap/doc/COLMAP.desktop".
Makefile:96: recipe for target 'install' failed
make: *** [install] Error 1

There are no such path of doc  and  COLMAP.desktop. 

I'm not sure if there's an impact.

**Comment by AIBluefisher** [comment]
It has been closed since this [pull request](https://github.com/AIBluefisher/GraphSfM/pull/15) has fixed it.
