### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by wolf943134497** [AIBluefisher/GraphSfM#17]
Hi @AIBluefisher   Thanks for your great work! 

[ 66%] Building CXX object src/base/CMakeFiles/pose_test.dir/pose_test.cc.o
make[2]: *** No rule to make target '/usr/local/lib/libgtest_main.a', needed by 'src/base/essen                                                                                                                tial_matrix_utils_test'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object src/base/CMakeFiles/essential_matrix_utils_test.dir/essential_matrix                                                                                                                _test.cc.o
CMakeFiles/Makefile2:916: recipe for target 'src/base/CMakeFiles/camera_database_test.dir/all'                                                                                                                 failed
make[1]: *** [src/base/CMakeFiles/camera_database_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:772: recipe for target 'src/base/CMakeFiles/visibility_pyramid_test.dir/al                                                                                                                l' failed
make[1]: *** [src/base/CMakeFiles/visibility_pyramid_test.dir/all] Error 2
CMakeFiles/Makefile2:1024: recipe for target 'src/base/CMakeFiles/database_cache_test.dir/all'                                                                                                                 failed
make[1]: *** [src/base/CMakeFiles/database_cache_test.dir/all] Error 2
CMakeFiles/Makefile2:808: recipe for target 'src/base/CMakeFiles/triangulation_test.dir/all' fa                                                                                                                iled
make[1]: *** [src/base/CMakeFiles/triangulation_test.dir/all] Error 2
CMakeFiles/Makefile2:736: recipe for target 'src/base/CMakeFiles/warp_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/warp_test.dir/all] Error 2
CMakeFiles/Makefile2:1132: recipe for target 'src/base/CMakeFiles/point3d_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/point3d_test.dir/all] Error 2
CMakeFiles/Makefile2:880: recipe for target 'src/base/CMakeFiles/track_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/track_test.dir/all] Error 2
CMakeFiles/Makefile2:1276: recipe for target 'src/base/CMakeFiles/similarity_transform_test.dir                                                                                                                /all' failed
make[1]: *** [src/base/CMakeFiles/similarity_transform_test.dir/all] Error 2
CMakeFiles/Makefile2:952: recipe for target 'src/base/CMakeFiles/essential_matrix_utils_test.di                                                                                                                r/all' failed
make[1]: *** [src/base/CMakeFiles/essential_matrix_utils_test.dir/all] Error 2
CMakeFiles/Makefile2:1096: recipe for target 'src/base/CMakeFiles/camera_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/camera_test.dir/all] Error 2
CMakeFiles/Makefile2:1060: recipe for target 'src/base/CMakeFiles/correspondence_graph_test.dir                                                                                                                /all' failed
make[1]: *** [src/base/CMakeFiles/correspondence_graph_test.dir/all] Error 2
CMakeFiles/Makefile2:988: recipe for target 'src/base/CMakeFiles/image_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/image_test.dir/all] Error 2
CMakeFiles/Makefile2:844: recipe for target 'src/base/CMakeFiles/undistortion_test.dir/all' fai                                                                                                                led
make[1]: *** [src/base/CMakeFiles/undistortion_test.dir/all] Error 2
CMakeFiles/Makefile2:1204: recipe for target 'src/base/CMakeFiles/pose_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/pose_test.dir/all] Error 2
CMakeFiles/Makefile2:1240: recipe for target 'src/base/CMakeFiles/projection_test.dir/all' fail                                                                                                                ed
make[1]: *** [src/base/CMakeFiles/projection_test.dir/all] Error 2
CMakeFiles/Makefile2:1168: recipe for target 'src/base/CMakeFiles/database_test.dir/all' failed
make[1]: *** [src/base/CMakeFiles/database_test.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

gtest cause this error, any suggestions? Thanks!

**Comment by AIBluefisher** [comment]
The cmake can't find gtest. Have you installed `gtest`?

**Comment by wolf943134497** [comment]
> The cmake can't find gtest. Have you installed `gtest`?

I have installed gtest, cmake Found GTest: /usr/include. another problem occured:
CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "warp_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target
  "visibility_pyramid_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "triangulation_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "undistortion_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "track_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "camera_database_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target
  "essential_matrix_utils_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "image_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "database_cache_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target
  "correspondence_graph_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "camera_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "point3d_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "database_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "pose_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "projection_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target
  "similarity_transform_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "camera_rig_test".


CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "graph_cut_test".


CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "cost_functions_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "line_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target
  "homography_matrix_utils_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "polynomial_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "gps_test".

CMake Error in src/base/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "camera_models_test".

CMake Error in src/exe/CMakeLists.txt:
  Specified unknown feature "cxx_std_11" for target "colmap_exe".

**Comment by AIBluefisher** [comment]
I suspect the the version of your cmake is low, I recommend you to upgrade your cmake to the newest.

**Comment by wolf943134497** [comment]
> I suspect the the version of your cmake is low, I recommend you to upgrade your cmake to the newest.

cmake 3.16.4 works! Thanks!
