### ISSUE TITLE
Need some help with the config.txt part of Distributed Approach

### ISSUE THREAD

**Issue by jchen706** [AIBluefisher/GraphSfM#27]
I have the config.txt file as 
```
`
server_num

0.0.0.0 8080 /home/a/castle/image

0.0.0.1 8080 /home/b/castle/image

`
```

the 0.0.0.0 is the IPv4 address,  8080 is the default port run by the application, last part is the image path.

Questions:
What is server_num?
Does the image path have to contain images or it can be empty folder?
Does the image path and the output path of the worker have to be the same?
Does the server or master IPv4 address have to be included in the config.txt?

**Comment by AIBluefisher** [comment]
- server_num is the number of your servers. Since you have two IPs, the server_num is simply 2. 
- The image path of worker does not need to contain images. It's used to store images that master transfered to server.
- Absolutely.
- Yes. Master should know the ip address of all workers, so it can distribute tasks to workers. Currently, I do not find a proper way to avoid setting the ip address.

**Comment by jchen706** [comment]
![image](https://user-images.githubusercontent.com/32785168/90439071-ea647f80-e0a2-11ea-996b-6e09168eedf4.png)

I am wondering what you use for the IP address. what linux command did you use to get the IP address?
I think port numbers are default to 8080 in the code

.sh file: 
`
/home/j/GraphSfM/build/src/exe/colmap distributed_mapper \
$DATASET_PATH/$log_folder \
--database_path=$DATASET_PATH/database.db \
--transfer_images_to_server=1 \
--image_path=$DATASET_PATH/images \
--output_path=$DATASET_PATH/$log_folder \
--config_file_name=/home/j/GraphSfM/scripts/shell/config.txt \
--num_workers=8 \
--distributed=1 \
--repartition=0 \
--assign_cluster_id=1 \
--write_binary=1 \
--retriangulate=0 \
--final_ba=1 \
--select_tracks_for_bundle_adjustment=1 \
--long_track_length_threshold=10 \
--num_images_ub=$num_images_ub \
--completeness_ratio=0.7 \
--relax_ratio=1.3 \
--cluster_type=NCUT # SPECTRA
//#--image_overlap=$image_overlap \
`

config.txt file
```
2
192.168.1.88 8080 /home/jccscs/GraphSfM/build/src/exe/output
192.168.1.140 8080 /home/j/gerrad-hall
```
Command ran ./distributed-mapper.sh /home/j/gerrad-hall  100 log /home/j/GraphSfM/scripts/shell

I also used the 10.0.2.15 from my virtual box, and 10.0.0.1 from my computer. Virtual box is on another device while computer is on Linux.

**Comment by Yzhbuaa** [comment]
> ![image](https://user-images.githubusercontent.com/32785168/90439071-ea647f80-e0a2-11ea-996b-6e09168eedf4.png)
> 
> I am wondering what you use for the IP address. what linux command did you use to get the IP address?
> I think port numbers are default to 8080 in the code
> 
> .sh file:
> `/home/j/GraphSfM/build/src/exe/colmap distributed_mapper \ $DATASET_PATH/$log_folder \ --database_path=$DATASET_PATH/database.db \ --transfer_images_to_server=1 \ --image_path=$DATASET_PATH/images \ --output_path=$DATASET_PATH/$log_folder \ --config_file_name=/home/j/GraphSfM/scripts/shell/config.txt \ --num_workers=8 \ --distributed=1 \ --repartition=0 \ --assign_cluster_id=1 \ --write_binary=1 \ --retriangulate=0 \ --final_ba=1 \ --select_tracks_for_bundle_adjustment=1 \ --long_track_length_threshold=10 \ --num_images_ub=$num_images_ub \ --completeness_ratio=0.7 \ --relax_ratio=1.3 \ --cluster_type=NCUT # SPECTRA //#--image_overlap=$image_overlap \`
> 
> config.txt file
> 
> ```
> 2
> 192.168.1.88 8080 /home/jccscs/GraphSfM/build/src/exe/output
> 192.168.1.140 8080 /home/j/gerrad-hall
> ```
> 
> Command ran ./distributed-mapper.sh /home/j/gerrad-hall 100 log /home/j/GraphSfM/scripts/shell
> 
> I also used the 10.0.2.15 from my virtual box, and 10.0.0.1 from my computer. Virtual box is on another device while computer is on Linux.

@jchen706 , hello, I met the same problem. How did you solve it? Thank you!
