### ISSUE TITLE
Large data set processing

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#28]
Hello, I wonder how many images can GraphSfM process at a time. Does GraphSfM have the potential to process millions of images at a time? Thank you.

**Comment by AIBluefisher** [comment]
It's no doubt that GraphSfM can handle millions of images, as long as you partition images to clusters that your computer can handle. But it also has requirements of your computer. The main limitation is the great memory requirement for image clustering, as I use NCut or spectral clustering first to solve the graph cut problem. You can see from the unit test in clustering module, I test at most 10,000 images with 1,000,000 edges on my computer with 16GB RAM. For more larger scale datasets, we can try other stategies to solve the graph cut problem. But you still need to ensure that your computer's memory is large enough.

**Comment by Yzhbuaa** [comment]
Thank you for your detailed explanation!
