### ISSUE TITLE
Efficiency problem

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#32]
Hello, I run the pipeline on my dataset, which contains **18,384 images**. The resolution of the images is **6000*4000**. The total time consumption is **49 hours** on my ubuntu server(Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz 64GB Nvidia GTX 2080TI). 

I noticed in the README.md file, that "Based on this work, we have been successfully **reconstructed Peking University (contains 12306 images) within 2 hours on a laptop**".

I am wondering what is the primary cause of the huge distinction of the time consumption.

Thank you!

**Comment by yuancaimaiyi** [comment]
@Yzhbuaa I test author code on my dataset ,the efficiency is very low, and the time is about twice that of the original version

**Comment by Yzhbuaa** [comment]
@yuancaimaiyi What is your experiment condition(the dataset and machine configuration)?

**Comment by yuancaimaiyi** [comment]
> @yuancaimaiyi What is your experiment condition(the dataset and machine configuration)?

@Yzhbuaa  my machine I7 2080 ti ,dataset is autodrive images(forward)
At the same time,I find paper same as the author---https://www.groundai.com/project/csfm-community-based-structure-from-motion/

**Comment by Yzhbuaa** [comment]
You mentioned 'original version'. Does the 'original version' refer to COLMAP? If so, do you use the same settings for feature extraction and feature matching?(e.g. using GPU for feature extraction, using vocab tree for feature matching).

**Comment by AIBluefisher** [comment]
> > @yuancaimaiyi What is your experiment condition(the dataset and machine configuration)?
> 
> @Yzhbuaa my machine I7 2080 ti ,dataset is autodrive images(forward)
> At the same time,I find paper same as the author---https://www.groundai.com/project/csfm-community-based-structure-from-motion/

There are some work used the same divide-and-conquer strategy, you can find them in the related work of my paper. But my paper is absolutely not the same as CSfM if you have read my paper. As CSfM used similarity averaging to stitch the model, it may degrade in some cases, because the relative similairty transformations are often not enough for l1 optimization. Thus I developed a graph-based strategy to merge sub-models.

**Comment by AIBluefisher** [comment]
> Hello, I run the pipeline on my dataset, which contains **18,384 images**. The resolution of the images is **6000*4000**. The total time consumption is **49 hours** on my ubuntu server(Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz 64GB Nvidia GTX 2080TI).
> 
> I noticed in the README.md file, that "Based on this work, we have been successfully **reconstructed Peking University (contains 12306 images) within 2 hours on a laptop**".
> 
> I am wondering what is the primary cause of the huge distinction of the time consumption.
> 
> Thank you!
It often depends on the density and resolution of the images. Besides, the size of each cluster can influence the reconstruction time. At last, I used a accelerated internal version for experiments, and I'm not able make it open-source due to copyright limitation.

**Comment by Yzhbuaa** [comment]
Thank you!

**Comment by yuancaimaiyi** [comment]
@AIBluefisher 
I'm just saying that CSFM uses the same idea. I don't have any other meaning. Thank you very much for your reply. At the same time, can you tell me what the internal acceleration principle is？
