### ISSUE TITLE
copyright infringement

### ISSUE THREAD

**Issue by rperrot** [AIBluefisher/GraphSfM#33]
Hi, 

I've just noticed that you use some code here : 

https://github.com/AIBluefisher/GraphSfM/blob/dev/src/clustering/kmeans.h

However this code originates from here (the functions, naming and even comments are the same) : 

https://github.com/openMVG/openMVG/blob/develop/src/openMVG/clustering/kmeans.hpp

And you removed the licence header. 

Please credits the original authors of the code.  

Thanks.

**Comment by AIBluefisher** [comment]
Thanks for your suggestion. I'm scheduling on updating all the copyright declaration.

**Comment by AIBluefisher** [comment]
The copyright has been updated in the code. Thanks for the contribution of OpenMVG to the community!
