### ISSUE TITLE
Segment the sparse point cloud regularly?

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#34]
@AIBluefisher. Hello, can I segment the sparse point cloud regularly(e.g. rectangular regions without overlap) using GraphSfM? Currently I find `point_cloud_segmenter`, but I also find there is overlap between regions after I segment sparse point cloud using `point_cloud_segmenter`.

As my goal is to obtain large scale mesh model. If I continue to perform Multi-View Stereo algorithm on these regions and further surface reconstruction algorithm, I will end up with several mesh models with overlap.

Could you please give me some suggestions? Thank you!

**Comment by AIBluefisher** [comment]
Segment point clouds by graph cut approaches could be much slow, thus I turn to cluster camera poses at first, then collect point clouds that are observed by cameras in the same cluster. If you want to segment point clouds without overlap, you can use a coarse-to-fine approach instead: first, use kd-tree to segment a large point cloud into several parts; then, use graph cut to cluster each part into smaller one. Actually, you can find this approach in ICCV 2017 paper: Distributed Very Large Scale Bundle Adjustment by Camera Consensus.

**Comment by Yzhbuaa** [comment]
Thank you! I will read the paper for more information.

**Comment by Yzhbuaa** [comment]
Is it possible to partition the scene like CMVS or method introduced by Maura, Massimo et al. using GraphSfM?
