### ISSUE TITLE
Completeness ratio too large?

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#38]
@AIBluefisher Hello, why do we need large completeness ratio(i.e. greater or equal than 0.5)?

**Comment by AIBluefisher** [comment]
Though there should be an ablation study to evaluate the completeness ratio, I found the parameter value contribute little to the accuracy of final reconstruction but the success of merging step. Larger completeness ratio can gaurantee more repetitive ares among inter clusters.
