### ISSUE TITLE
The reconstruction time in "Graph-Based Parallel Large Scale Structure from Motion"

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#39]
@AIBluefisher. Hello, What does the reconstruction time mean in your paper "Graph-Based Parallel Large Scale Structure from Motion"? Does it include the time of feature extraction, feature matching, image clustering, local incremental SfM and final global bundle adjustment? Thank you!

**Comment by AIBluefisher** [comment]
Feature extraction and matching time are simply ignored in our paper.

**Comment by Yzhbuaa** [comment]
Thank you!
