### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by utc1205** [AIBluefisher/GraphSfM#4]
![791308564](https://user-images.githubusercontent.com/13039604/50410384-95238c80-0833-11e9-8dc1-2681e135ef84.jpg)
I fellow the command: 
cd GraphSfM
mkdir build && cd build
cmake -D CUDA_USE_STATIC_CUDA_RUNTIME=OFF ..
make -j4
But when the project is built to 95%, it breaks.  
Does it have relation with opencv version? My opencv version is 4.0.
Can anybody knows how to deal with it ?
Thanks and wish your reply.!

**Comment by utc1205** [comment]
![build](https://user-images.githubusercontent.com/13039604/50413054-3f58df80-0847-11e9-9073-783d5ba6d315.jpg)
this is my building message by make

**Comment by AIBluefisher** [comment]
OpenCV 4 is not supported right now, try OpenCV 3. I’ll modify README for the recommended version of OpenCV.

**Comment by utc1205** [comment]
Can you tell me your opencv version, I want to keep consistent with you.

**Comment by AIBluefisher** [comment]
My OpenCV version is 3.2.

**Comment by utc1205** [comment]
Thank you so much for reply
