### ISSUE TITLE
cmake error: could not find gtest

### ISSUE THREAD

**Issue by Yzhbuaa** [AIBluefisher/GraphSfM#42]
@AIBluefisher, hello, I compiled the newest version of DAGSfM, and I encountered the problem following when I run `cmake ..`:

> -- Check for gtest
> CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
>   GTEST_MAIN_LIBRARY)

I've encountered the same problem several times. And finally I solved it with `sudo apt-get install libgtest-dev`. I guess the libgtest-dev should be one of the `Basic Requirements` mentioned in the README.

**Comment by AIBluefisher** [comment]
try the following command.
```sh
cd /usr/src/gtest
sudo mkdir build
cd build
sudo cmake ..
sudo make
sudo cp libgtest* /usr/lib/
cd ..
sudo rm -rf build
```

**Comment by Yzhbuaa** [comment]
I just tried the method and it solved my problem successfully. Thank you!
