### ISSUE TITLE
only one worker run in distributed mode

### ISSUE THREAD

**Issue by Haonan-DONG** [AIBluefisher/GraphSfM#49]
Thanks for the work of distributed mode. I managed to compile it. However, I only got one worker running while configuring three workers. Here are the details.
1. When I compiled the code, I **change the src/map_reduce/worker.h line 47 to line 55 to (change the std to std_1)**
```
namespace std_1
{
  template <typename T, typename... Ts>
  std::unique_ptr<T> make_unique(Ts &&...params)
  {
    return std::unique_ptr<T>(new T(std::forward<Ts>(params)...));
  }
} // namespace std
```
Since I got an ambiguous issue with make_unique, and I also **add c++ standard 14 into the CMakeLists.txt**

2. For running the binary, I firstly run the script to feature extraction and matching. Then I run the distributed_sfm.sh both in sequential mode and distributed mode. The sequential mode got the correct result, However, only one worker worked in distributed mode. Here are my config file.

![Screenshot from 2021-05-11 14-29-37](https://user-images.githubusercontent.com/42935157/117768740-5dcba400-b265-11eb-8014-203d577f0dae.png)

and my distributed_sfm.sh:
![Screenshot from 2021-05-11 14-30-38](https://user-images.githubusercontent.com/42935157/117768832-83f14400-b265-11eb-89e1-0d33b365a566.png)

and I run the script with

```
./distributed_sfm.sh path_to_imgs 200
```
Evey time the master (192.168.17.126 also the worker) only allocated the to the first worker in the config.txt.
![Screenshot from 2021-05-11 14-34-11](https://user-images.githubusercontent.com/42935157/117769205-fa8e4180-b265-11eb-8cd2-b3724b813369.png)
The data set have exactly 375 images.

So, is my configuration step error?

Thanks.

**Comment by Haonan-DONG** [comment]
the IP I wrote should be 192.168.217.*, and please ignore the mistake.

**Comment by Haonan-DONG** [comment]
And the resource monitor picture run with the different config.txt, which only contain the last two workers.

**Comment by Haonan-DONG** [comment]
I fixed it, since the number of cluster is an int variable, thus  the total size of image is 375, and I set the num_img_up is 200, which means that the cluster will be set to 1. I probably misunderstand the usage of the number of up bound.
![Screenshot from 2021-05-11 16-19-06](https://user-images.githubusercontent.com/42935157/117783151-db4ae080-b274-11eb-8c99-a11e666aa62b.png)

And about the change in 1 of make_unique, I found out that the c++ 14 includes the make_unique, so in my machines, I compile them with c++14 and eliminated the code for defining the make_unique.

Thanks. And I will close the issue.

**Comment by coder12333444** [comment]
@Haonan-DONG  sorry to bother you ! I want to know how to set config.txt ,I am confused about the IP and Port ,your port is 9124,how to get it ? 
thanks

**Comment by Haonan-DONG** [comment]
Never mind.
As I mentioned in the question area, the "config.txt" should consist of two parts.
In the first part, it should be the number of workers you want to deploy. Since here I set 2, so the monitor only has 2 nodes running. If you want 3 workers, set it 3.
In the second part, it should be the workers' information: IP \t port \t path_to_data.
The IP should be the workers' IP, and port is a random integer lower than 65535. And I think you can set random one in the range of 1024 to 65535. If it fails, please check your firewall. It might block away some IPs.

Last, If you only have one machine, set the workers' IP as the master's IP and just use different ports. And you are good.

**Comment by coder12333444** [comment]
@Haonan-DONG 

As you said, when there is only one machine, use different port, but code report error!
![error](https://user-images.githubusercontent.com/87088407/126784647-bb5315c9-833b-4959-96fe-a97370be143c.png)
Isn't IP  obtained by ifconfig?
