### ISSUE TITLE
after Merging Clusters ,coordinate  error?

### ISSUE THREAD

**Issue by coder12333444** [AIBluefisher/GraphSfM#51]
@AIBluefisher  sorry to bother you! I use DAGSFM run my data , final result is not correct, but the result of the partition is correct. I did not optimize the camera intrinsics during reconstruction, and I use  gps constraint ,so each partition result align gps-coordinate . You can see that Figure 1 is the result of partition 3, the coordinate system and Thecamera intrinsics are correct, but the final merged result is shown in Figure 2. The coordinates seem to be normalized and the final camera intrinsics have optimized. May I need to modify the result parameters of the merged version to ensure that my final result is correct?
figure 1 is correct :
![g1](https://user-images.githubusercontent.com/87088407/126782575-711fc66e-1a74-479d-a680-63db3948155b.png)
figure 2 merge final result is error:
![g2](https://user-images.githubusercontent.com/87088407/126782601-d7bc461c-5c43-416b-be7f-d8aaf6cf8d53.png)

**Comment by AIBluefisher** [comment]
hi，the intrinsics are optimized after merging the local sfm results, see line 532-534 in https://github.com/AIBluefisher/DAGSfM/blob/dev/src/controllers/distributed_mapper_controller.cpp. You can set all options to false to keep them being fixed.

**Comment by coder12333444** [comment]
@AIBluefisher  thanks ,I have solved it, and at the same time I found that your program replaces colmap trakcs with the union find algorithm，awesome job,what do you think can be improved in the follow-up of your DAGSFM??????????????????????????

**Comment by AIBluefisher** [comment]
Well, there could be plenty of work I would like to do. The track building module is actually not added to the pipeline, but I have been managing to use it to filter/correct wrong feature matches. Besides, the robustness and efficiency of the local incremental SfM could be further improved. Also, the bundle adjustment refinement could be accelerated by developing a distributed algorithm. The distributed module should also be refactored to support more features, like fault tolerance and load balancing.

**Comment by coder12333444** [comment]
@AIBluefisher fine !!! 
I think the furture work that can be improved are as follows:
1. Feature extraction and matching
2. Implement hybrid sfm based on distributed sfm
In addition, is there any recommendation in the literature that supports the panoramic camera model? I want to support the panoramic camera, but the models in the paper are all strange

**Comment by coder12333444** [comment]
@AIBluefisher 
About distributed mode, I set config.txt,but the program is stuck here,like this :
![dis](https://user-images.githubusercontent.com/87088407/127131440-2af943e5-25a4-47e5-948a-aa1a109f4ce8.png)
I am confused !
thanks
