### ISSUE TITLE
Image pairs：0

### ISSUE THREAD

**Issue by xycai-pku** [AIBluefisher/GraphSfM#54]
I follow the  tutorial and run on several datasets but got the same error。
![error](https://user-images.githubusercontent.com/57410921/135020064-fc13a938-4473-414b-8c07-d2c997f01d5c.png)
I didn‘t install the Python Modules， does this matter？

**Comment by yamiefun** [comment]
Hi @xycai-pku , I meet the same problem. Have you solved it?

**Comment by xycai-pku** [comment]
> 

Sorry, I didn‘t insist on it and the problem still remains.

**Comment by AIBluefisher** [comment]
Note that features should be extracted at first, or the similarity searching step does nothing.

**Comment by yamiefun** [comment]
@xycai-pku i checkout the repo to master branch and everything works lol.

**Comment by xycai-pku** [comment]
> 

Thanks for your advices! I will try it later.
