### ISSUE TITLE
compare with openMVG

### ISSUE THREAD

**Issue by zzxp** [AIBluefisher/GraphSfM#6]
hi ,I see you compared with openMVG as shown in the picture,I want to know that is it the Incremental sfm way in openMVG?

![image](https://user-images.githubusercontent.com/26996462/50670861-23a0c680-1009-11e9-95ac-54f0085f2fa1.png)

**Comment by zzxp** [comment]
I use the Incremental Pipeline in openMVG to deal with dataset that include 1000 images, generate much more 3D points than you and cost much more time than you

**Comment by AIBluefisher** [comment]
Yes, we compared with incremental pipeline in openMVG. Sometimes the incremental pipeline of openMVG may produce more 3D points than our approach, due to longer tracks to produce more stable 3D points. It's vary to datasets. In our tested datasets, we do produce more 3D points than OpenMVG.

**Comment by zzxp** [comment]
ok  thanks

**Comment by zyxrrr** [comment]
Hello!
I run OpenMVG and your code on Tanks and Temples Benchmark. Your code seems spends two times in both Sequential and Global Pipeline, is it normal?
