### ISSUE TITLE
About depth range and depth interval of sparse point cloud

### ISSUE THREAD

**Issue by yao520131415926** [AIBluefisher/GraphSfM#7]
Thank you for your open source! 
I am trying to compute depth ranges and depth interval of the sparse point cloud. Could you please give me some idea on how to get these information?

**Comment by AIBluefisher** [comment]
As the sparse point clouds locate in 3D space, the z-coordinate is the depth value. Thus, you can just traverse all the 3D points to extract their depth value. The code may seem like below:
```C++
for (auto it = sfm_data.structures.begin(); it != sfm_data.structures.end(); ++it) {
    Landmark landmark = it->second;
    Eigen::Vector3d X = landmark.X;
    // Your code here to do what you want with X[2]
}
```

**Comment by yao520131415926** [comment]
Thank you so much for your help!
