### ISSUE TITLE
测试数据集

### ISSUE THREAD

**Issue by Young532042725** [AIBluefisher/GraphSfM#9]
您好，能提供一下数据集测试吗？

**Comment by AIBluefisher** [comment]
https://github.com/AIBluefisher/ComputerVisionDatasets/tree/master/3d_reconstruction

**Comment by Young532042725** [comment]
谢谢您

**Comment by Young532042725** [comment]
您好，请教您一个问题，我使用www.diegm.uniud.it/~fusiello/demo/samantha/中的PiazzaBraNew.zip数据集，按照教程运行，提取特征点可以进行，完了之后出现如下提示，能帮我看看什么原因吗？　谢谢您
![Screenshot from 2019-04-02 15-09-01](https://user-images.githubusercontent.com/34529308/55388838-9537d480-5566-11e9-979c-4865140fff3f.png)
![Screenshot from 2019-04-02 15-07-53](https://user-images.githubusercontent.com/34529308/55388844-9b2db580-5566-11e9-95bd-b1d5435bcdd6.png)

**Comment by AIBluefisher** [comment]
It's really a bug in my code, I'll fix it as soon as possible. However, I'm busy on something else right now, so  it would be a time for updating the code.

**Comment by AIBluefisher** [comment]
Hi, an new version of our GraphSfM is under deploying, this issue has been fixed and the new version may be released at the end in this month. May you take attention.

**Comment by Young532042725** [comment]
@AIBluefisher Hi, The GraphSfM hasn't been updated yet?

**Comment by AIBluefisher** [comment]
there are some modules to detatch due to authorities, I have to delay the released version.

在 2019-05-05 11:51:47，yjs <notifications@github.com> 写信：

**Comment by waitwaitwaitforME** [comment]
@AIBluefisher Hi, could you please tell me when GraphSfM will be updated？

**Comment by AIBluefisher** [comment]
Hi, the newest version has been released in a new repo: https://github.com/AIBluefisher/EGSfM . 

Welcome to use and report issues!​
